# Site settings
title: Preeti Bhandari
description: 'Taking on the world, one algorithm at a time'
url: 'http://preetibhandari.site'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Preeti Bhandari'
  email: preeti.bhandari@nyu.edu
  #twitter_username: joshgerdes
  #facebook_username: joshgerdes
  #about_username:  HaydonLisa
  projects_username: projects
  goodreads_username: preeti1205
  leetcode_username: pb1771
  hackerrank_username: preeti_bhandari
  github_username:  preeti1205
  linkedin_username:  preeti-bhandari-036470104

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: 
  - jekyll-paginate
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor/bundle']